### ISSUE TITLE
Subscribe Component

### ISSUE THREAD

**Issue by AugmentBLU** [responsiv/spark-theme#1]
Hello,

I want to use October for a new site that will be in development very soon and I like how Laravel Spark handles subscriptions so naturally I'm keen on your version for October. Do you know when the subscription side will be available or know roughly if/when this theme will be complete?

I see the requirement for the Pay plugin and this works, however I'm not seeing the subscribe/planList plugin anywhere?

Thanks,
Ross

**Comment by w20k** [comment]
@AugmentBLU this one - https://github.com/responsiv/subscribe-plugin ?

**Comment by daftspunk** [comment]
This theme accompanies this plugin: https://github.com/responsiv/subscribe-plugin

Although it is an unfinished piece of work
